### ISSUE TITLE
[Wandb + Validation Helper] ValueError: This table expects 3 columns: ['Prompt', '1024x1024', 'Mean Luminance'], found 12

### ISSUE THREAD

**Issue by BuildBackBuehler** [bghira/SimpleTuner#370]
```
2024-04-25 15:05:34,078 [DEBUG] (validation) Resolutions for validation: [('1024', '1024')]
2024-04-25 15:05:34,078 [INFO] (validation) Processing width/height: 1024x1024
2024-04-25 15:24:03,664 [DEBUG] (validation) Completed generating image: 
2024-04-25 15:24:03,666 [DEBUG] (validation) Validation image: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
2024-04-25 15:24:03,666 [DEBUG] (TextEmbeddingCache) Initialising validations...
2024-04-25 15:24:03,666 [DEBUG] (TextEmbeddingCache) Hashing caption: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
2024-04-25 15:24:03,666 [DEBUG] (TextEmbeddingCache) -> b9e2146868bf415405f516faa0e4f3e3-sdxl
2024-04-25 15:24:03,666 [DEBUG] (TextEmbeddingCache) (Rank: 0) (id=textembeds) (uncached_prompts=[], is_validation=False, return_concat=True)
2024-04-25 15:24:03,667 [DEBUG] (TextEmbeddingCache) Hashing caption: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
2024-04-25 15:24:03,667 [DEBUG] (TextEmbeddingCache) -> b9e2146868bf415405f516faa0e4f3e3-sdxl
2024-04-25 15:24:03,667 [DEBUG] (TextEmbeddingCache) Processing file: /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/ffs/cache_house/text_embeds/b9e2146868bf415405f516faa0e4f3e3-sdxl.pt, prompt: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
 -> filtered prompt: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
2024-04-25 15:24:03,667 [DEBUG] (LocalDataBackend) Checking if /Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/build/ffs/cache_house/text_embeds/b9e2146868bf415405f516faa0e4f3e3-sdxl.pt exists = True
2024-04-25 15:24:03,673 [DEBUG] (TextEmbeddingCache) Returning output: (tensor([[[-3.6406, -2.3750,  3.8906,  ...,  0.1367,  0.4590, -0.2969],
         [ 0.3789,  0.6133,  0.2422,  ...,  0.0947,  0.4004,  0.2695],
         [-0.3359, -0.2793,  0.7188,  ...,  0.3691,  0.2891,  0.3945],
         ...,
         [-0.4922,  0.0293, -0.6484,  ..., -0.0630,  0.0049,  0.6719],
         [-0.4883,  0.0264, -0.6562,  ..., -0.1660, -0.1475,  0.6094],
         [-0.5078,  0.0415, -0.5703,  ..., -0.1426, -0.3184,  0.6641]]],
       dtype=torch.bfloat16), tensor([[ 0.3789, -1.5547,  0.1157,  ..., -0.1138, -2.0625,  1.6719]],
       dtype=torch.bfloat16))
2024-04-25 15:24:24,581 [DEBUG] (validation) Resolutions for validation: [('1024', '1024')]
2024-04-25 15:24:24,582 [INFO] (validation) Processing width/height: 1024x1024
2024-04-25 15:46:29,513 [DEBUG] (validation) Completed generating image: Scandalous papparazzi photo of the most seductive woman: Florence Pugh
2024-04-25 15:46:29,525 [DEBUG] (validation) Prompt unconditional has 10 images
2024-04-25 15:46:29,525 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x5313AB490>
2024-04-25 15:46:29,741 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x5DC909B10>
2024-04-25 15:46:29,987 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x5DD8F16D0>
2024-04-25 15:46:30,255 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x5DC64D7D0>
2024-04-25 15:46:30,460 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x5D3521ED0>
2024-04-25 15:46:30,719 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x361A862D0>
2024-04-25 15:46:30,963 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x379545E50>
2024-04-25 15:46:31,231 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x12E94BFD0>
2024-04-25 15:46:31,557 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x37965BCD0>
2024-04-25 15:46:31,801 [DEBUG] (validation) Adding to table: <PIL.Image.Image image mode=RGB size=1024x1024 at 0x37967C450>

Traceback (most recent call last):
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/train_sdxl.py", line 1587, in main
    log_validations(
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/helpers/legacy/validation.py", line 571, in log_validations
    table.add_data(prompt_shortname, *wandb_images, mean_luminance)
  File "/Users/zack/.home/gitrepos/ComfyUI/.venv/lib/python3.11/site-packages/wandb/data_types.py", line 396, in add_data
    raise ValueError(
ValueError: This table expects 3 columns: ['Prompt', '1024x1024', 'Mean Luminance'], found 12
```

I'm guessing that in Log_Validations (around Lines 501 to 571) the data for the validationshortname isn't being rolled in, which would account for 7-8ish extra arguments/columns? I'll probably roll back my Validations.py and give 'er another go. 

Iterations are taking wildly long, 30 step DDIM. First validation image took about 18 mins. Don't know if that's normal or not, but the lack of progress bar for the iteration made me think it stalled out, luckily I didn't touch it and know that for future ref.

**Comment by bghira** [comment]
you probably have validation torch compile enabled still

**Comment by bghira** [comment]
i also think that error is fixed in the master branch, let me know if it's not. you might want to set validation interval to like 5 steps for testing it

**Comment by BuildBackBuehler** [comment]
> i also think that error is fixed in the master branch, let me know if it's not. you might want to set validation interval to like 5 steps for testing it
> 
> the fixed problem is due to multiple images per shortname, not sure if you have the number of images for each validation > 1 or not

No torch compile enabled, only "extra" was --vae_cache_preprocess. 

I am on the the master branch AFAIK. 

That last 'un would definitely be the issue, though! I have 10 validation images/run, so 2 per epoch. So I'll just need to do 1 per epoch or ?

**Comment by BuildBackBuehler** [comment]
Eeek. Still an issue unfortunately (with 1 validation image per epoch)

```
Generating validation images: 1it [09:30, 570.04s/it]Traceback (most recent call last):
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/train_sdxl.py", line 1633, in <module>
    main()
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/train_sdxl.py", line 1587, in main
    log_validations(
  File "/Users/zack/.home/gitrepos/ComfyUI/SimpleTuner/helpers/legacy/validation.py", line 571, in log_validations
    table.add_data(prompt_shortname, *wandb_images, mean_luminance)
  File "/Users/zack/.home/gitrepos/ComfyUI/.venv/lib/python3.11/site-packages/wandb/data_types.py", line 396, in add_data
    raise ValueError(
ValueError: This table expects 3 columns: ['Prompt', '1024x1024', 'Mean Luminance'], found 7
```

Got the time down by 1/2 thanks to DDPM, at least.

**Comment by bghira** [comment]
yeah, i've been trying and i can't reproduce the fault with the latest code on SDXL, SD 2.x or DeepFloyd validations

**Comment by BuildBackBuehler** [comment]
Hm interesting, because it did happen again. But I just pulled in the latest updates and am testing again. Used  --cache_clear_validation_prompts on this 3rd attempt, no luck. I'm going to clear my cache, I'm 80% sure that'll do the trick honestly

**Comment by bghira** [comment]
num validation images might have an actual problem in the implementation. setting it to 1 should work

**Comment by bghira** [comment]
![image](https://github.com/bghira/SimpleTuner/assets/59658056/e989fd84-09bd-4682-8f4a-bfc26a0d794c)

**Comment by BuildBackBuehler** [comment]
Were you running a training sesh with epochs at all? My final attempt with epochs ended by finishing epoch 1, creating the 1 validation image and training abruptly finishing. 

I just ran it with training_steps instead and it is working as intended it seems. 

<img width="1677" alt="image" src="https://github.com/bghira/SimpleTuner/assets/116780517/0d9c6be5-b48d-4d88-b895-01701dc3a103">

I prefer epochs because its a concrete concept (rounds of image repeats performed). I don't know if I am missing something but I have no grasp of what the steps of num_training_steps entail. And in my ignorance, I hoped epochs would allow for adaptable step amounts based on the "difficulty" of the picture or what not (though I'm sure its constant regardless of my wish 😂)

**Comment by bghira** [comment]
carefully read the info output of the trainer, it explains how it arrived at its conclusions of the step count, etc. it can get complicated but for the most part it doesn't matter, just do a number of steps and see how it goes
